if(EXISTS "/root/CSDIY/database/build_support/test/binder_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/binder_test[1]_tests.cmake")
else()
  add_test(binder_test_NOT_BUILT binder_test_NOT_BUILT)
endif()
