if(EXISTS "/root/CSDIY/database/build_support/test/clock_replacer_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/clock_replacer_test[1]_tests.cmake")
else()
  add_test(clock_replacer_test_NOT_BUILT clock_replacer_test_NOT_BUILT)
endif()
