if(EXISTS "/root/CSDIY/database/build_support/test/extendible_htable_page_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/extendible_htable_page_test[1]_tests.cmake")
else()
  add_test(extendible_htable_page_test_NOT_BUILT extendible_htable_page_test_NOT_BUILT)
endif()
