if(EXISTS "/root/CSDIY/database/build_support/test/trie_debug_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/trie_debug_test[1]_tests.cmake")
else()
  add_test(trie_debug_test_NOT_BUILT trie_debug_test_NOT_BUILT)
endif()
