if(EXISTS "/root/CSDIY/database/build_support/test/tuple_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/tuple_test[1]_tests.cmake")
else()
  add_test(tuple_test_NOT_BUILT tuple_test_NOT_BUILT)
endif()
