if(EXISTS "/root/CSDIY/database/build_support/test/txn_index_concurrent_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/txn_index_concurrent_test[1]_tests.cmake")
else()
  add_test(txn_index_concurrent_test_NOT_BUILT txn_index_concurrent_test_NOT_BUILT)
endif()
