if(EXISTS "/root/CSDIY/database/build_support/test/txn_executor_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/txn_executor_test[1]_tests.cmake")
else()
  add_test(txn_executor_test_NOT_BUILT txn_executor_test_NOT_BUILT)
endif()
