if(EXISTS "/root/CSDIY/database/build_support/test/txn_scan_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/txn_scan_test[1]_tests.cmake")
else()
  add_test(txn_scan_test_NOT_BUILT txn_scan_test_NOT_BUILT)
endif()
