if(EXISTS "/root/CSDIY/database/build_support/test/type_test[1]_tests.cmake")
  include("/root/CSDIY/database/build_support/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
